# Change these first
owner: ConfluxBot # Your GitHub username
repo: upt # Your GitHub repository name

# Add your sites here
sites:
  - name: Confluxscan
    url: https://confluxscan.io
  - name: Shuttleflow
    url: https://shuttleflow.io
  - name: Conflux Netowrk
    url: https://confluxnetwork.org
  - name: Conflux Bounty
    url: https://bounty.conflux-chain.org

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  theme: dark
  baseUrl: /upt
  logoUrl: https://raw.githubusercontent.com/ConfluxBot/upt/master/assets/2021-03-25_10-34-02_conflux-logo-min.png
  name: Conflux UPT
  introTitle: "**Conflux UTP**"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
